# Generated by Django 3.2.12 on 2023-01-12 06:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('observations', '0003_observation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('form_data', models.JSONField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', easy_thumbnails.fields.ThumbnailerImageField(upload_to='observations')),
                ('record_id', models.UUIDField()),
                ('record_type', models.ForeignKey(limit_choices_to={'model__in': []}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('form_data', models.JSONField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gps_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('identity', models.CharField(max_length=40)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.recordimage')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.definition')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjectrecord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='subjectmonitoringrecord',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='subjectmonitoringrecord',
            name='monitoring_definition',
        ),
        migrations.RemoveField(
            model_name='subjectmonitoringrecord',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='subjectmonitoringrecord',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ObservationImage',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectMonitoringRecord',
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.recordimage'),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='monitoring_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.monitoringdefinition'),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoringrecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.subjectrecord'),
        ),
    ]
