# Generated by Django 3.2.12 on 2023-05-18 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('observations', '0004_auto_20230112_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordUploadFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='observations')),
                ('record_id', models.UUIDField()),
                ('file_type', models.CharField(max_length=100)),
                ('record_type', models.ForeignKey(limit_choices_to={'model__in': []}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
