# Generated by Django 3.2.12 on 2023-12-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_recorduploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrecord',
            name='origin_form_data',
            field=models.JSONField(default=dict),
        ),
    ]
