# base image
FROM public.ecr.aws/g0x0v6d0/python-gdal-magic:latest

ARG SOURCE_DIR=/usr/local/src/python-gdal

# DB vars
ENV DB_USER ${DB_USER}
ENV DB_NAME ${DB_NAME}
ENV DB_HOST ${DB_HOST}
ENV DB_PORT ${DB_PORT}
ENV DB_PASSWORD ${DB_PASSWORD}

ENV DJANGO_SECRET_KEY ${DJANGO_SECRET_KEY}
ENV DJANGO_DEBUG ${DJANGO_DEBUG}

ENV REDIS_HOST ${REDIS_HOST}
ENV REDIS_PORT ${REDIS_PORT}

ENV FCM_DRY_RUN ${FCM_DRY_RUN}
ENV USE_S3 ${USE_S3}
ENV FIREBASE_PRIVATE_KEY ${FIREBASE_PRIVATE_KEY}
ENV DASHBOARD_URL ${DASHBOARD_URL}
ENV CELERY_BROKER_URL ${CELERY_BROKER_URL}

ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV AWS_STORAGE_BUCKET_NAME ${AWS_STORAGE_BUCKET_NAME}
ENV AWS_S3_REGION_NAME ${AWS_S3_REGION_NAME}

ENV EMAIL_DOMAIN ${EMAIL_DOMAIN}
ENV EMAIL_HOST ${EMAIL_HOST}
ENV EMAIL_HOST_USER ${EMAIL_HOST_USER}
ENV EMAIL_HOST_PASSWORD ${EMAIL_HOST_PASSWORD}

ENV DockerHome /usr/src/app

RUN mkdir -p $DockerHome

WORKDIR $DockerHome

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

ARG CPLUS_INCLUDE_PATH=/usr/include/gdal
ARG C_INCLUDE_PATH=/usr/include/gdal

COPY . $DockerHome
RUN python3 -m pip install --upgrade pip --no-cache-dir \
    && python3 -m pip install GDAL --no-cache-dir \
    && python3 -m pip install -r requirements.txt --no-cache-dir

EXPOSE 8000

ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
