# Generated by Django 3.2.12 on 2022-08-25 08:27

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerField(upload_to='attachments'),
        ),
    ]
