# Generated by Django 3.2.12 on 2022-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedefinition',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casedefinition',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
