# Generated by Django 3.2.12 on 2022-07-11 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseStateMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reporttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseStateTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("form_data", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StateDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_default", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StateStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_start_state", models.BooleanField(blank=True, default=False)),
                ("is_stop_state", models.BooleanField(blank=True, default=False)),
                (
                    "state_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.statedefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StateTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("form_definition", models.JSONField(blank=True, null=True)),
                (
                    "from_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_transitions",
                        to="cases.statestep",
                    ),
                ),
                (
                    "to_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_transitions",
                        to="cases.statestep",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="statustemplatemapping",
            name="report_type",
        ),
        migrations.RemoveField(
            model_name="statustemplatemapping",
            name="status_template",
        ),
        migrations.RemoveField(
            model_name="case",
            name="status_template",
        ),
        migrations.DeleteModel(
            name="StatusHistory",
        ),
        migrations.DeleteModel(
            name="StatusTemplate",
        ),
        migrations.DeleteModel(
            name="StatusTemplateMapping",
        ),
        migrations.AddField(
            model_name="casestatetransition",
            name="transition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cases.statetransition"
            ),
        ),
        migrations.AddField(
            model_name="casestatemapping",
            name="state_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.statedefinition"
            ),
        ),
        migrations.AddField(
            model_name="casestate",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.case"
            ),
        ),
        migrations.AddField(
            model_name="casestate",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cases.statestep"
            ),
        ),
        migrations.AddField(
            model_name="casestate",
            name="transition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.casestatetransition",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="state_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.statedefinition",
            ),
        ),
        migrations.AddConstraint(
            model_name="casestatemapping",
            constraint=models.UniqueConstraint(
                fields=("state_definition", "report_type"),
                name="case_state_mapping_unique_ids",
            ),
        ),
    ]
