# Generated by Django 3.2.12 on 2022-07-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reporternotification'),
        ('cases', '0002_auto_20220711_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='reports.incidentreport'),
        ),
        migrations.AlterField(
            model_name='casestate',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.casestatetransition'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='from_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='cases.statestep'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='to_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='cases.statestep'),
        ),
    ]
