# Generated by Django 3.2.12 on 2022-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20220711_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
