# Generated by Django 3.2.12 on 2022-07-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_reporttype_state_definition'),
        ('accounts', '0011_auto_20220718_0928'),
        ('cases', '0004_case_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=300)),
                ('title_template', models.TextField(blank=True)),
                ('body_template', models.TextField(blank=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype')),
                ('state_transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.statetransition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('to', models.TextField(blank=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.authority')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.notificationtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
