# Generated by Django 3.2.12 on 2022-07-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_authoritynotification_notificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('rep', 'Report'), ('ptc', 'Promote to case'), ('cas', 'Case transition')], default='cas', max_length=3),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='state_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.statetransition'),
        ),
    ]
