# Generated by Django 3.2.12 on 2022-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='outbreak_plan_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('REP', 'Report'), ('PTC', 'Promote to case'), ('CAS', 'Case transition')], default='CAS', max_length=3),
        ),
    ]
