# Generated by Django 3.2.12 on 2023-03-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20221121_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
