# Generated by Django 4.2.30 on 2026-07-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_move_census_models_to_census_state"),
        ("census", "0003_row_backed_animal_facts_remove_species"),
    ]

    operations = [
        migrations.CreateModel(
            name="CensusRoundDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ANIMAL", "Animal"), ("HUMAN", "Human")],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("TRAINING", "Training"),
                        ],
                        default="PRODUCTION",
                        max_length=20,
                    ),
                ),
                (
                    "repeat",
                    models.CharField(
                        choices=[("ANNUAL", "Annual")], default="ANNUAL", max_length=20
                    ),
                ),
                ("census_period_start", models.CharField(max_length=5)),
                ("census_period_end", models.CharField(max_length=5)),
                ("start_date", models.CharField(max_length=5)),
                ("soft_finish_date", models.CharField(max_length=5)),
                ("hard_finish_date", models.CharField(max_length=5)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "target_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="census_round_definitions",
                        to="accounts.authority",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_censusrounddefinition",
                "ordering": ("kind", "mode", "code"),
            },
        ),
        migrations.AddField(
            model_name="villagecensussnapshot",
            name="round_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXPLICIT", "Explicit"),
                    ("INFERRED", "Inferred"),
                    ("ADMIN_OVERRIDE", "Admin override"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CensusRoundOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("year", models.PositiveIntegerField()),
                ("occurrence_key", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ANIMAL", "Animal"), ("HUMAN", "Human")],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("TRAINING", "Training"),
                        ],
                        max_length=20,
                    ),
                ),
                ("census_period_start", models.DateField()),
                ("census_period_end", models.DateField()),
                ("start_date", models.DateField()),
                ("soft_finish_date", models.DateField()),
                ("hard_finish_date", models.DateField()),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="census.censusrounddefinition",
                    ),
                ),
                (
                    "target_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="census_round_occurrences",
                        to="accounts.authority",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_censusroundoccurrence",
                "ordering": ("start_date", "definition__code"),
            },
        ),
        migrations.AddField(
            model_name="villagecensussnapshot",
            name="round_occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshots",
                to="census.censusroundoccurrence",
            ),
        ),
        migrations.AddConstraint(
            model_name="censusroundoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("definition", "year"),
                name="unique_active_census_round_occurrence_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="censusroundoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("occurrence_key",),
                name="unique_active_census_round_occurrence_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="censusrounddefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("code",),
                name="unique_active_census_round_definition_code",
            ),
        ),
    ]
