# Generated by Django 4.0.1 on 2022-02-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220127_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'ordering': ('name',), 'verbose_name_plural': 'Authorities'},
        ),
        migrations.AlterModelOptions(
            name='authorityuser',
            options={'verbose_name': 'Authority User'},
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('from_date', models.DateTimeField()),
                ('through_date', models.DateTimeField()),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviations', to='accounts.authority')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_%(class)s', to='accounts.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
