# Generated by Django 4.0.1 on 2022-02-09 08:42

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_category_options_remove_category_domain_and_more'),
        ('accounts', '0005_alter_authority_options_alter_authorityuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authorityuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='authority',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='authorityuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='authorityuser',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='authorityuser',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='authorityuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
