# Generated by Django 3.2.12 on 2022-07-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityuser',
            name='role',
            field=models.CharField(blank=True, choices=[('REP', 'Reporter'), ('OFC', 'Officer')], default='REP', max_length=3),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='role',
            field=models.CharField(blank=True, default='REP', max_length=3, verbose_name=[('REP', 'Reporter'), ('OFC', 'Officer')]),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.authority'),
        ),
    ]
