# Generated by Django 3.2.12 on 2023-08-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_configuration_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='boundary_connects',
            field=models.ManyToManyField(blank=True, related_name='authority_boundary_connects', to='accounts.Authority'),
        ),
    ]
