# Generated by Django 3.2.12 on 2023-10-13 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_authority_boundary_connects"),
    ]

    operations = [
        migrations.RunSQL("create sequence accounts_authorityuser_username_seq;")
    ]
