# Generated by Django 3.2.12 on 2023-12-07 06:45

import accounts.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_username_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=accounts.models.path_and_rename),
        ),
    ]
