# Generated by Django 3.2.12 on 2026-05-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='villages',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='accounts.Village'),
        ),
        migrations.CreateModel(
            name='VillageReporterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_assignments', to='accounts.authorityuser')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_assignments', to='accounts.village')),
            ],
        ),
        migrations.AddConstraint(
            model_name='villagereporterassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('reporter', 'village'), name='unique_active_village_reporter_assignment'),
        ),
    ]
