# Generated by Django 3.2.12 on 2026-05-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20260505_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCensusFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('animal_quantity', models.PositiveIntegerField(default=0)),
                ('household_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('species__sort_order', 'species__name'),
            },
        ),
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='villagereporterassignment',
            name='census_role',
            field=models.CharField(choices=[('OFF', 'Official'), ('VOL', 'Volunteer')], default='OFF', max_length=3),
        ),
        migrations.CreateModel(
            name='VillageCensusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('census_date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='census_snapshots', to='accounts.authorityuser')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='census_snapshots', to='accounts.village')),
            ],
            options={
                'ordering': ('-census_date', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='animalspecies',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_animal_species_code'),
        ),
        migrations.AddField(
            model_name='animalcensusfact',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='accounts.villagecensussnapshot'),
        ),
        migrations.AddField(
            model_name='animalcensusfact',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='census_facts', to='accounts.animalspecies'),
        ),
        migrations.AddConstraint(
            model_name='animalcensusfact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('snapshot', 'species'), name='unique_active_census_fact_species'),
        ),
    ]
