# Generated by Codex on 2026-05-19

from django.db import migrations, models
import django.db.models.deletion


def migrate_animal_fact_measures(apps, schema_editor):
    AnimalCensusFact = apps.get_model("accounts", "AnimalCensusFact")
    for fact in AnimalCensusFact.objects.select_related("animal_species").order_by("id"):
        species = fact.animal_species
        fact.row_key = f"species:{species.code}" if species else ""
        fact.measures = {
            "animal_quantity": fact.animal_quantity,
            "household_quantity": fact.household_quantity,
        }
        fact.extra_dimensions = {}
        fact.save(update_fields=["row_key", "measures", "extra_dimensions"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_auto_20260505_0539"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="animalcensusfact",
            name="unique_active_census_fact_species",
        ),
        migrations.CreateModel(
            name="CensusDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ANIMAL", "Animal"), ("HUMAN", "Human")],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "kind"),
            },
        ),
        migrations.AddField(
            model_name="villagecensussnapshot",
            name="form_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="villagecensussnapshot",
            name="status",
            field=models.CharField(
                choices=[("SUBMITTED", "Submitted")], default="SUBMITTED", max_length=20
            ),
        ),
        migrations.CreateModel(
            name="CensusDefinitionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("schema", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="accounts.censusdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("definition__sort_order", "definition__kind", "-version"),
            },
        ),
        migrations.AddConstraint(
            model_name="censusdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("kind",),
                name="unique_active_census_definition_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="censusdefinitionversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("definition", "version"),
                name="unique_active_census_definition_version",
            ),
        ),
        migrations.AddField(
            model_name="villagecensussnapshot",
            name="definition_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshots",
                to="accounts.censusdefinitionversion",
            ),
        ),
        migrations.RenameField(
            model_name="animalcensusfact",
            old_name="species",
            new_name="animal_species",
        ),
        migrations.AddField(
            model_name="animalcensusfact",
            name="row_key",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animalcensusfact",
            name="extra_dimensions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="animalcensusfact",
            name="measures",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(migrate_animal_fact_measures, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="animalcensusfact",
            name="animal_quantity",
        ),
        migrations.RemoveField(
            model_name="animalcensusfact",
            name="household_quantity",
        ),
        migrations.AlterModelOptions(
            name="animalcensusfact",
            options={
                "ordering": (
                    "animal_species__sort_order",
                    "animal_species__name",
                    "row_key",
                )
            },
        ),
        migrations.AddConstraint(
            model_name="animalcensusfact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("snapshot", "row_key"),
                name="unique_active_animal_census_fact_row",
            ),
        ),
        migrations.CreateModel(
            name="HumanCensusFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("row_key", models.CharField(max_length=100)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("measures", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_facts",
                        to="accounts.villagecensussnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("row_key",),
            },
        ),
        migrations.CreateModel(
            name="CurrentAnimalCensusFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_pointer",
                        to="accounts.animalcensusfact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentHumanCensusFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_pointer",
                        to="accounts.humancensusfact",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="humancensusfact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("snapshot", "row_key"),
                name="unique_active_human_census_fact_row",
            ),
        ),
    ]
