# Generated by Django 4.0.1 on 2022-02-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='reporttype',
            name='domain',
        ),
    ]
