# Generated by Django 3.2.12 on 2022-03-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_followupreport_incidentreport_zeroreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupreport',
            old_name='rendered_data',
            new_name='renderer_data',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='origin_rendered_data',
            new_name='origin_renderer_data',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='rendered_data',
            new_name='renderer_data',
        ),
    ]
