# Generated by Django 3.2.12 on 2022-03-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20220319_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='renderer_data_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
