# Generated by Django 3.2.12 on 2022-03-19 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0006_reporttype_renderer_data_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreport',
            name='test_flag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followupreports', to='reports.reporttype'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentreports', to='reports.reporttype'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='reports')),
                ('report_id', models.UUIDField()),
                ('report_type', models.ForeignKey(limit_choices_to={'model__in': []}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='followupreport',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.image'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.image'),
        ),
    ]
