# Generated by Django 3.2.12 on 2022-05-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20220319_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
