# Generated by Django 3.2.12 on 2022-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_feature"),
        ("reports", "0008_auto_20220502_0543"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="relevant_authorities",
            field=models.ManyToManyField(
                related_name="incidents", to="accounts.Authority"
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="relevant_authority_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
