# Generated by Django 3.2.12 on 2022-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20220701_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='case_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
