# Generated by Django 3.2.12 on 2022-07-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reporternotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporternotification',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reporttype'),
        ),
    ]
