# Generated by Django 3.2.12 on 2022-07-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_is_finished'),
        ('reports', '0012_reporternotification_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='state_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.statedefinition'),
        ),
    ]
