# Generated by Django 3.2.12 on 2022-10-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20220825_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporternotification',
            name='title_template',
            field=models.TextField(blank=True),
        ),
    ]
