# Generated by Django 3.2.12 on 2022-12-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0016_reporternotification_title_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportView",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "reports_aggregate_view",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS reports_aggregate_view;
            CREATE VIEW reports_aggregate_view AS
                SELECT
                    reports_zeroreport.id,
                    reports_zeroreport.created_at,
                    reports_zeroreport.reported_by_id AS reported_by_id
                FROM reports_zeroreport
                UNION ALL
                SELECT
                    reports_incidentreport.id,
                    reports_incidentreport.created_at,
                    reports_incidentreport.reported_by_id AS reported_by_id
                FROM reports_incidentreport
                UNION ALL
                SELECT
                    reports_followupreport.id,
                    reports_followupreport.created_at,
                    reports_followupreport.reported_by_id AS reported_by_id
                FROM reports_followupreport
            """
        ),
    ]
