# Generated by Django 3.2.12 on 2023-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_reporttype_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='is_followable',
            field=models.BooleanField(default=False),
        ),
    ]
