# Generated by Django 3.2.12 on 2023-05-07 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0020_reporttype_is_followable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='reports')),
                ('report_id', models.UUIDField()),
                ('file_type', models.CharField(max_length=100)),
                ('report_type', models.ForeignKey(limit_choices_to={'model__in': []}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
