# Generated by Django 3.2.12 on 2023-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='definition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
