# Generated by Django 4.2.30 on 2026-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0024_reporttype_metric_accumulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="ai_suspected",
            field=models.TextField(blank=True, default=""),
        ),
    ]
