# Generated by Django 4.2.30 on 2026-08-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0025_incidentreport_ai_suspected"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttype",
            name="close_definition",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
