# Generated by Django 4.2.30 on 2026-08-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_authorityuser_gender_age"),
        ("reports", "0026_layered_case_close"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incident_reports",
                to="accounts.village",
            ),
        ),
    ]
