# Generated by Django 3.2.12 on 2026-06-02 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(max_length=100)),
                ('required_scope', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('external_action_id', models.CharField(blank=True, max_length=200)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('request_headers_summary', models.JSONField(blank=True, default=dict)),
                ('result_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REPLAYED', 'Replayed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='ACCEPTED', max_length=20)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=80)),
                ('integration_type', models.CharField(choices=[('AI_ASSISTANT', 'AI assistant'), ('CLUSTER_DETECTOR', 'Cluster detector'), ('RISK_EVALUATOR', 'Risk evaluator'), ('GENERIC', 'Generic')], default='GENERIC', max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('scope_codes', models.JSONField(blank=True, default=list)),
                ('allowed_callback_domains', models.JSONField(blank=True, default=list)),
                ('rate_limit_policy', models.JSONField(blank=True, default=dict)),
                ('oauth_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='integration_client', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('report.submitted', 'Report submitted'), ('followup.submitted', 'Followup submitted'), ('case.promoted', 'Case promoted'), ('case.state_changed', 'Case state changed'), ('cluster.evaluation_requested', 'Cluster evaluation requested'), ('risk.evaluation_requested', 'Risk evaluation requested')], default='report.submitted', max_length=80)),
                ('schema_version', models.CharField(default='2026-06-02', max_length=40)),
                ('source_app', models.CharField(max_length=80)),
                ('subject_type', models.CharField(max_length=80)),
                ('subject_id', models.CharField(max_length=120)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('produced_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RECORDED', 'Recorded'), ('QUEUED', 'Queued'), ('CANCELLED', 'Cancelled')], default='RECORDED', max_length=20)),
            ],
            options={
                'ordering': ('-produced_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('schema_version', models.CharField(default='2026-06-02', max_length=40)),
                ('active_signing_secret_ref', models.CharField(blank=True, max_length=300)),
                ('active_signing_secret_version', models.PositiveIntegerField(default=1)),
                ('next_signing_secret_ref', models.CharField(blank=True, max_length=300)),
                ('next_signing_secret_version', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('integration_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='integrations.integrationclient')),
            ],
            options={
                'ordering': ('integration_client__code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERING', 'Delivering'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body_summary', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signing_secret_version', models.PositiveIntegerField(default=1)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.integrationevent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('key', models.CharField(max_length=200)),
                ('action_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('request_payload_hash', models.CharField(max_length=64)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_record', to='integrations.integrationactionlog')),
                ('integration_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='integrations.integrationclient')),
            ],
            options={
                'verbose_name_plural': 'integration idempotency records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='integrationactionlog',
            name='integration_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_logs', to='integrations.integrationclient'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('integration_client', 'name'), name='unique_active_webhook_endpoint_name'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('event', 'endpoint'), name='unique_active_webhook_delivery_event_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='integrationidempotencyrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('integration_client', 'action_type', 'key'), name='unique_active_integration_idempotency_action_key'),
        ),
        migrations.AddConstraint(
            model_name='integrationclient',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_integration_client_code'),
        ),
    ]
