# Generated by Django 3.2.12 on 2026-06-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('target_type', models.CharField(choices=[('report', 'Report'), ('case', 'Case'), ('cluster', 'Cluster')], max_length=20)),
                ('target_id', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('factors', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('rule_engine', 'Rule engine'), ('external_risk_evaluator', 'External risk evaluator'), ('ai', 'AI'), ('human', 'Human')], max_length=40)),
                ('evaluator_version', models.CharField(blank=True, max_length=120)),
                ('external_assessment_id', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('integration_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to='integrations.integrationclient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='risk_assessment_target_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['target_type', 'target_id', 'is_current'], name='risk_assessment_current_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['integration_client', 'external_assessment_id'], name='risk_assessment_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('target_type', 'target_id'), name='unique_current_risk_assessment_target'),
        ),
    ]
