# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_auto_20260602_0547"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="integrationevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("event_type", "report.submitted"),
                    ("source_app", "reports"),
                    ("subject_type", "reports.IncidentReport"),
                ),
                fields=("event_type", "source_app", "subject_type", "subject_id"),
                name="unique_active_report_submitted_event_subject",
            ),
        ),
    ]
