# Generated by Django 3.2.12 on 2026-06-02 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_incidentreport_definition'),
        ('integrations', '0003_unique_report_submitted_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('staff', 'Staff')], default='staff', max_length=20)),
                ('external_action_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.JSONField(blank=True, default=dict)),
                ('integration_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_comments', to='integrations.integrationclient')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_comments', to='reports.incidentreport')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='integrationreportcomment',
            index=models.Index(fields=['report', '-created_at'], name='int_report_comment_report_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationreportcomment',
            index=models.Index(fields=['integration_client', 'external_action_id'], name='int_report_cmt_external_idx'),
        ),
    ]
