# Generated by Django 4.2.30 on 2026-06-02 09:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_auto_20260602_0654"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationClusterResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "cluster_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("external_cluster_id", models.CharField(max_length=200)),
                ("algorithm_version", models.CharField(max_length=120)),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                ("incident_ids", models.JSONField(blank=True, default=list)),
                ("authority_ids", models.JSONField(blank=True, default=list)),
                ("village_ids", models.JSONField(blank=True, default=list)),
                ("geometry", models.JSONField(blank=True, null=True)),
                (
                    "radius_meters",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cluster_results",
                        to="integrations.integrationactionlog",
                    ),
                ),
                (
                    "integration_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cluster_results",
                        to="integrations.integrationclient",
                    ),
                ),
            ],
            options={
                "ordering": ("-window_start", "-window_end", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["integration_client", "external_cluster_id"],
                        name="int_cluster_external_idx",
                    ),
                    models.Index(
                        fields=["cluster_id"], name="int_cluster_cluster_id_idx"
                    ),
                    models.Index(
                        fields=["risk_level", "-window_start"],
                        name="int_cluster_risk_window_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="integrationclusterresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("integration_client", "external_cluster_id"),
                name="unique_active_integration_cluster_external",
            ),
        ),
    ]
