# Generated by Django 4.2.30 on 2026-06-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0005_integrationclusterresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="risk_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
