# Generated by Codex on 2026-06-11

from django.db import migrations, models
import django.db.models.deletion


def delete_existing_risk_assessments(apps, schema_editor):
    RiskAssessment = apps.get_model("integrations", "RiskAssessment")
    RiskAssessment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0022_incidentreport_definition"),
        ("integrations", "0006_riskassessment_created_by"),
    ]

    operations = [
        migrations.RunPython(
            delete_existing_risk_assessments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="riskassessment",
            name="unique_current_risk_assessment_target",
        ),
        migrations.RemoveIndex(
            model_name="riskassessment",
            name="risk_assessment_target_idx",
        ),
        migrations.RemoveIndex(
            model_name="riskassessment",
            name="risk_assessment_current_idx",
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_assessments",
                to="reports.incidentreport",
            ),
        ),
        migrations.RemoveField(
            model_name="riskassessment",
            name="target_id",
        ),
        migrations.RemoveField(
            model_name="riskassessment",
            name="target_type",
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["report", "-created_at"],
                name="risk_assessment_report_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["report", "is_current"],
                name="risk_assessment_current_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskassessment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("is_current", True),
                ),
                fields=("report",),
                name="unique_current_risk_assessment_report",
            ),
        ),
    ]
