# Generated by Django 4.2.30 on 2026-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_report_risk_assessment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationevent',
            name='event_type',
            field=models.CharField(choices=[('report.submitted', 'Report submitted'), ('followup.submitted', 'Followup submitted'), ('case.promoted', 'Case promoted'), ('case.state_changed', 'Case state changed'), ('cluster.evaluation_requested', 'Cluster evaluation requested'), ('risk.evaluation_requested', 'Risk evaluation requested'), ('ai.evaluation_requested', 'AI evaluation requested')], default='report.submitted', max_length=80),
        ),
    ]
