# Generated by Django 3.2.12 on 2022-11-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_place'),
        ('cases', '0008_auto_20221121_1052'),
        ('reports', '0016_reporternotification_title_template'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('zone1_color', models.CharField(blank=True, max_length=7)),
                ('zone1_radius', models.FloatField(blank=True, null=True)),
                ('zone1_message_title', models.CharField(blank=True, max_length=200)),
                ('zone1_message_body', models.TextField(blank=True)),
                ('zone2_color', models.CharField(blank=True, max_length=7)),
                ('zone2_radius', models.FloatField(blank=True, null=True)),
                ('zone2_message_title', models.CharField(blank=True, max_length=200)),
                ('zone2_message_body', models.TextField(blank=True)),
                ('zone3_color', models.CharField(blank=True, max_length=7)),
                ('zone3_radius', models.FloatField(blank=True, null=True)),
                ('zone3_message_title', models.CharField(blank=True, max_length=200)),
                ('zone3_message_body', models.TextField(blank=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttype')),
                ('state_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.statestep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('color', models.CharField(max_length=7)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_places', to='cases.case')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outbreaks.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_messages', to='cases.case')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.message')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outbreaks.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
