# Generated by Django 3.2.12 on 2022-11-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_place'),
        ('outbreaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='outbreaks.plan'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreak_places', to='accounts.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='outbreaks.plan'),
        ),
    ]
